"""PDF Export for Bank/Investor-Ready Reports."""
import io
from datetime import datetime
from typing import Dict, Any, Optional
import pandas as pd

try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
    from reportlab.lib.enums import TA_CENTER, TA_LEFT
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False


def generate_investor_report_pdf(
    data: pd.DataFrame,
    kpis: Dict[str, Any],
    health_score: Dict[str, Any],
    company_name: str = "Your Business"
) -> Optional[bytes]:
    """
    Generate a professional PDF report for banks/investors.
    
    Args:
        data: Business data DataFrame
        kpis: Key performance indicators dict
        health_score: Business health score dict
        company_name: Company name for header
        
    Returns:
        PDF bytes or None if reportlab not installed
    """
    if not REPORTLAB_AVAILABLE:
        return None
    
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=0.75*inch, leftMargin=0.75*inch)
    styles = getSampleStyleSheet()
    story = []
    
    # Title
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        spaceAfter=6,
        alignment=TA_CENTER
    )
    story.append(Paragraph(f"{company_name} — Business Intelligence Report", title_style))
    story.append(Paragraph(f"Generated {datetime.now().strftime('%B %d, %Y')}", styles['Normal']))
    story.append(Spacer(1, 0.3*inch))
    
    # Executive Summary
    story.append(Paragraph("Executive Summary", styles['Heading2']))
    total_rev = kpis.get('total_revenue', data['revenue'].sum() if 'revenue' in data.columns else 0)
    margin = data['profit_margin'].mean() if 'profit_margin' in data.columns else 40
    score = health_score.get('score', 0)
    status = health_score.get('status', 'N/A')
    
    summary_text = f"""
    This report summarizes key performance metrics for {company_name}.
    <br/><br/>
    <b>Total Revenue:</b> ${total_rev:,.0f}
    <br/>
    <b>Profit Margin:</b> {margin:.1f}%
    <br/>
    <b>Business Health Score:</b> {score}/100 ({status})
    <br/><br/>
    Data reflects the most recent 12 months of business activity.
    """
    story.append(Paragraph(summary_text, styles['Normal']))
    story.append(Spacer(1, 0.2*inch))
    
    # Key Metrics Table
    story.append(Paragraph("Key Metrics", styles['Heading2']))
    
    metrics_data = [
        ['Metric', 'Value'],
        ['Total Revenue', f"${total_rev:,.0f}"],
        ['Profit Margin', f"{margin:.1f}%"],
        ['ROAS', f"{data['roas'].mean():.1f}x" if 'roas' in data.columns else 'N/A'],
        ['Avg Order Value', f"${(data['revenue'].sum()/data['orders'].sum()):.0f}" if 'orders' in data.columns and data['orders'].sum() > 0 else 'N/A'],
        ['Business Health', f"{score}/100"],
    ]
    
    t = Table(metrics_data, colWidths=[3*inch, 2*inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.black),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.3*inch))
    
    # Revenue Trend (simplified)
    if 'revenue' in data.columns and 'date' in data.columns and len(data) > 0:
        try:
            story.append(Paragraph("Revenue Trend (Last 12 Months)", styles['Heading2']))
            df = data.copy()
            df['date'] = pd.to_datetime(df['date'])
            monthly = df.set_index('date').resample('ME').sum()
            if 'revenue' in monthly.columns and len(monthly) > 0:
                rev_data = [['Month', 'Revenue']]
                for idx, row in monthly.tail(12).iterrows():
                    rev_data.append([idx.strftime('%Y-%m'), f"${row['revenue']:,.0f}"])
                t2 = Table(rev_data, colWidths=[2*inch, 2*inch])
                t2.setStyle(TableStyle([
                    ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                    ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                    ('GRID', (0, 0), (-1, -1), 0.5, colors.black),
                ]))
                story.append(t2)
        except Exception:
            pass
    
    story.append(Spacer(1, 0.3*inch))
    story.append(Paragraph("This report was generated by Echolon AI. For questions, contact your account manager.", styles['Normal']))
    
    doc.build(story)
    return buffer.getvalue()


def generate_excel_report(
    data: pd.DataFrame,
    kpis: Dict,
    health_score: Dict,
    company_name: str = "Your Business"
) -> Optional[bytes]:
    """Generate Excel business report. No external deps beyond pandas+openpyxl."""
    try:
        import io
        output = io.BytesIO()
        with pd.ExcelWriter(output, engine='openpyxl') as writer:
            total_rev = kpis.get('total_revenue', data['revenue'].sum() if 'revenue' in data.columns else 0)
            margin = data['profit_margin'].mean() if 'profit_margin' in data.columns else 40
            summary = pd.DataFrame([
                ['Company', company_name],
                ['Report Date', datetime.now().strftime('%Y-%m-%d')],
                ['Total Revenue', f"${total_rev:,.0f}"],
                ['Profit Margin', f"{margin:.1f}%"],
                ['Health Score', f"{health_score.get('score', 0)}/100"],
            ], columns=['Metric', 'Value'])
            summary.to_excel(writer, sheet_name='Summary', index=False)
            if 'date' in data.columns and 'revenue' in data.columns:
                monthly = data.copy()
                monthly['date'] = pd.to_datetime(monthly['date'])
                monthly['month'] = monthly['date'].dt.to_period('M').astype(str)
                agg = monthly.groupby('month')['revenue'].sum().reset_index()
                agg.to_excel(writer, sheet_name='Revenue by Month', index=False)
            data.head(500).to_excel(writer, sheet_name='Raw Data', index=False)
        return output.getvalue()
    except Exception:
        return None


def create_excel_download_button(
    data: pd.DataFrame,
    kpis: Dict,
    health_score: Dict,
    company_name: str = "Your Business",
    key: str = "excel_export"
):
    """Create Streamlit download button for Excel report."""
    import streamlit as st
    excel_bytes = generate_excel_report(data, kpis, health_score, company_name)
    if excel_bytes:
        st.download_button(
            label="📊 Download Report (Excel)",
            data=excel_bytes,
            file_name=f"echolon_report_{datetime.now().strftime('%Y%m%d')}.xlsx",
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            key=key,
            use_container_width=True
        )
    else:
        st.warning("Excel export requires `pip install openpyxl`.")


def create_pdf_download_button(
    data: pd.DataFrame,
    kpis: Dict,
    health_score: Dict,
    company_name: str = "Your Business",
    key: str = "pdf_export"
):
    """Create Streamlit download button for PDF report."""
    import streamlit as st
    
    pdf_bytes = generate_investor_report_pdf(data, kpis, health_score, company_name)
    if pdf_bytes:
        st.download_button(
            label="📄 Download Investor Report (PDF)",
            data=pdf_bytes,
            file_name=f"echolon_investor_report_{datetime.now().strftime('%Y%m%d')}.pdf",
            mime="application/pdf",
            key=key,
            use_container_width=True
        )
    else:
        st.warning("PDF export requires `pip install reportlab`. Install to enable.")
